#!/bin/bash

cd

mkdir grubSplashImages
cd grubSplashImages

wget -O default-URL-list.txt https://raw.githubusercontent.com/MaximumEndurance/grub-random/master/default-URL-list.txt
wget -i default-URL-list.txt
sudo rm default-URL-list.txt #Note has to be above update-grub. Caused a error on 10-Apr-17
sudo chmod 777 ../grubSplashImages/*	# replacing read write execute permissions for grubSplashImages directory
sudo chmod 777 ../grubSplashImages

## replacing the ?raw=true tag from each file. It is possibly causing errors with grub-bootloader, sice all files extension must end with .jpg, .png, etc.  formats

for file in $PWD/*
do
new_name=${file%?raw=true*}
mv $file $new_name
done

file="/etc/default/grub"

sudo sed -i 's/.*export.*//' $file
sudo sed -i 's/.*grubImage.*//' $file ## safety precaution. If the user runs the script multiple times it would create multiple entries in /etc/default/grub file
command="grubImage=\`ls \$PWD/\$grubImage | sort -R | tail -\$N | head -1\` \n
export GRUB_BACKGROUND=\"\$PWD/\$grubImage\" "


sudo echo -e $command >> $file

## Making changes permanent
## So update-grub runs everytime on bootup and a new random image is selected
file2="/etc/rc.local"
sed -i 's/sudo update-grub//' $file2  # removing redundant entires
sed -i 's/exit 0//' $file2

 ## entering commands into /etc/default/grub

sudo echo "sudo update-grub" >> /etc/rc.local
echo 'exit 0' >> /etc/rc.local
sudo update-grub	# update entries in grub for the first time


echo "Successfully Established grub-random"
